# Generated by Django 4.0.4 on 2022-05-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.FileField(upload_to='couverture/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='avartar',
            field=models.FileField(upload_to='avatar/'),
        ),
    ]
