# Generated by Django 4.0.4 on 2022-05-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partage',
            old_name='books',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='telecharge',
            old_name='books',
            new_name='book',
        ),
    ]
