# Generated by Django 4.0.4 on 2022-07-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-07-24T16:23:18.641514Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='datepub',
            field=models.CharField(default='10/03/2022 00:00:00.0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='couvertures/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
