# Generated by Django 4.0.4 on 2022-06-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='fichier',
            field=models.FileField(blank=True, upload_to='document/'),
        ),
    ]
