# Generated by Django 4.0.4 on 2022-06-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_books_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='fichier',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
