# Generated by Django 4.0.4 on 2022-06-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_books_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='datepub',
            field=models.DateField(null=True),
        ),
    ]
